# Generated by Django 4.2.2 on 2023-08-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_shippingaddress_orderitem_order_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
